export const CATALOG_EXTRAS = [
    {
        title: 'Wings of Fire — APJ Abdul Kalam',
        description: 'Inspirational autobiography bestseller for students and professionals.',
        category: 'books',
        brand: 'Universities Press',
        price: 18,
        stock: 120,
        images: ['https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400'],
        rating: 4.8,
    },
    {
        title: 'Rich Dad Poor Dad — Robert Kiyosaki',
        description: 'Personal finance classic paperback edition.',
        category: 'books',
        brand: 'Plata Publishing',
        price: 22,
        stock: 85,
        images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400'],
        rating: 4.6,
    },
    {
        title: 'The Alchemist — Paulo Coelho',
        description: 'International fiction novel, English paperback.',
        category: 'books',
        brand: 'HarperCollins',
        price: 15,
        stock: 200,
        images: ['https://images.unsplash.com/photo-1543002588-bfa74002ed6e?w=400'],
        rating: 4.7,
    },
    {
        title: 'NCERT Science Textbook Class 10',
        description: 'Official NCERT school textbook for CBSE students.',
        category: 'books',
        brand: 'NCERT',
        price: 12,
        stock: 300,
        images: ['https://images.unsplash.com/photo-1497633769703-9d55499f9955?w=400'],
        rating: 4.5,
    },
    {
        title: 'Steelbird SBA-1 Flip-Up Helmet',
        description: 'ISI certified full-face helmet for bikes and scooters.',
        category: 'automotive',
        brand: 'Steelbird',
        price: 89,
        stock: 45,
        images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400'],
        rating: 4.3,
    },
    {
        title: '70mai Pro Dashcam 4K Front & Rear',
        description: 'Wi-Fi dash camera with night vision and parking mode.',
        category: 'automotive',
        brand: '70mai',
        price: 129,
        stock: 32,
        images: ['https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=400'],
        rating: 4.4,
    },
    {
        title: '3M Car Polish & Scratch Remover',
        description: 'Professional grade car polish for exterior paint protection.',
        category: 'automotive',
        brand: '3M',
        price: 24,
        stock: 90,
        images: ['https://images.unsplash.com/photo-1489824914134-5ef044b2b8a8?w=400'],
        rating: 4.2,
    },
    {
        title: 'Michelin Pilot Sport 4 Tyre 195/55 R16',
        description: 'Premium tubeless car tyre with superior wet grip.',
        category: 'automotive',
        brand: 'Michelin',
        price: 145,
        stock: 18,
        images: ['https://images.unsplash.com/photo-1619642751034-765df43d7c18?w=400'],
        rating: 4.6,
    },
    {
        title: 'Universal Car Floor Mats Set of 4',
        description: 'All-weather rubber mats for sedan and SUV.',
        category: 'automotive',
        brand: 'AutoStyle',
        price: 35,
        stock: 60,
        images: ['https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=400'],
        rating: 4.1,
    },
    {
        title: 'Car Mobile Charger Dual USB 3.0',
        description: 'Fast charging adapter for car cigarette lighter socket.',
        category: 'automotive',
        brand: 'boAt',
        price: 19,
        stock: 150,
        images: ['https://images.unsplash.com/photo-1598327105666-5b89351aff23?w=400'],
        rating: 4.0,
    },
];
