/**
 * Maps UI search slugs → DB categories / title patterns
 *
 * DB categories that actually exist:
 *   automotive, beauty, books, fragrances, furniture, groceries,
 *   home-decoration, kitchen-accessories, laptops, mens-shirts,
 *   mens-shoes, mens-watches, mobile-accessories, motorcycle,
 *   skin-care, smartphones, sports-accessories
 */
export type SearchProfile = {
    categories?: string[];
    titleTerms?: string[];
    excludeTitlePatterns?: string[];
};

export const SEARCH_PROFILES: Record<string, SearchProfile> = {

    // ── Electronics ──────────────────────────────────────────────────────────
    electronics:                    { categories: ['laptops', 'smartphones', 'mobile-accessories'] },
    mobile:                         { categories: ['smartphones'] },
    mobiles:                        { categories: ['smartphones'] },
    smartphones:                    { categories: ['smartphones'] },
    laptops:                        { categories: ['laptops'] },
    'gaming laptops':               { categories: ['laptops'] },
    'desktop pcs':                  { categories: ['laptops'] },
    monitors:                       { categories: ['laptops'] },
    tablets:                        { categories: ['tablets', 'smartphones'] },
    'apple ipads':                  { categories: ['tablets', 'smartphones'] },
    'mobile accessories':           { categories: ['mobile-accessories'] },
    'mobile cases':                 { categories: ['mobile-accessories'] },
    'headphones & headsets':        { categories: ['mobile-accessories'] },
    headphones:                     { categories: ['mobile-accessories'] },
    earphones:                      { categories: ['mobile-accessories'] },
    'power banks':                  { categories: ['mobile-accessories'] },
    screenguards:                   { categories: ['mobile-accessories'] },
    'memory cards':                 { categories: ['mobile-accessories'] },
    'smart headphones':             { categories: ['mobile-accessories'] },
    'mobile cables':                { categories: ['mobile-accessories'] },
    'mobile chargers':              { categories: ['mobile-accessories'] },
    'mobile holders':               { categories: ['mobile-accessories'] },
    'smart wearable tech':          { categories: ['mens-watches'] },
    'smart watches':                { categories: ['mens-watches'] },
    'smart glasses (vr)':           { categories: ['mobile-accessories'] },
    'smart bands':                  { categories: ['mens-watches'] },
    'health care appliances':       { categories: ['kitchen-accessories'] },
    'bp monitors':                  { categories: ['kitchen-accessories'] },
    'weighing scale':               { categories: ['kitchen-accessories'] },
    'gaming & accessories':         { categories: ['laptops', 'mobile-accessories'] },
    'computer accessories':         { categories: ['mobile-accessories', 'laptops'] },
    'external hard disks':          { categories: ['mobile-accessories'] },
    pendrives:                      { categories: ['mobile-accessories'] },
    'laptop skins & decals':        { categories: ['mobile-accessories'] },
    'laptop bags':                  { categories: ['mobile-accessories'] },
    mouse:                          { categories: ['mobile-accessories'] },
    'computer peripherals':         { categories: ['mobile-accessories'] },
    'printers & ink cartridges':    { categories: ['mobile-accessories'] },
    cameras:                        { categories: ['mobile-accessories'] },
    'dslr & mirrorless':            { categories: ['mobile-accessories'] },
    'compact & bridge cameras':     { categories: ['mobile-accessories'] },
    'sports & action':              { categories: ['mobile-accessories'] },
    'camera accessories':           { categories: ['mobile-accessories'] },
    lens:                           { categories: ['mobile-accessories'] },
    tripods:                        { categories: ['mobile-accessories'] },
    speakers:                       { categories: ['mobile-accessories'] },
    'home audio speakers':          { categories: ['mobile-accessories'] },
    'home theatre':                 { categories: ['mobile-accessories'] },
    soundbars:                      { categories: ['mobile-accessories'] },
    'bluetooth speakers':           { categories: ['mobile-accessories'] },
    'dth set top box':              { categories: ['mobile-accessories'] },
    'smart home automation':        { categories: ['home-decoration', 'mobile-accessories'] },
    'google nest':                  { categories: ['mobile-accessories'] },
    'network components':           { categories: ['mobile-accessories'] },
    routers:                        { categories: ['mobile-accessories'] },
    televisions:                    { categories: ['televisions', 'appliances'] },
    television:                     { categories: ['televisions', 'appliances'] },
    'smart tvs':                    { categories: ['televisions'] },

    // ── TVs & Appliances ─────────────────────────────────────────────────────
    appliances:                     { categories: ['appliances'] },
    'tvs & appliances':             { categories: ['televisions', 'appliances'] },
    'new launches':                 { categories: ['televisions', 'appliances'] },
    'new launch':                   { categories: ['televisions', 'appliances'] },
    'smart & ultra hd':             { categories: ['televisions'] },
    'shop by screen size':          { categories: ['televisions'] },
    '24 & below':                   { categories: ['televisions'] },
    '28 - 32':                      { categories: ['televisions'] },
    '39 - 43':                      { categories: ['televisions'] },
    '49 - 55':                      { categories: ['televisions'] },
    '60 & above':                   { categories: ['televisions'] },
    'shop by brand':                { categories: ['televisions', 'appliances'] },
    'buying guides':                { categories: ['televisions', 'appliances'] },
    'top brands':                   { categories: ['televisions', 'appliances', 'smartphones', 'laptops'] },
    'washing machine':              { categories: ['appliances'], titleTerms: ['washing', 'washer'] },
    'washing machines':             { categories: ['appliances'], titleTerms: ['washing', 'washer'] },
    'refrigerator':                 { categories: ['appliances'], titleTerms: ['refrigerator', 'fridge'] },
    'fully automatic front load':   { categories: ['appliances'], titleTerms: ['fully automatic', 'front load'] },
    'semi automatic top load':      { categories: ['appliances'], titleTerms: ['semi automatic', 'top load'] },
    'fully automatic top load':     { categories: ['appliances'], titleTerms: ['fully automatic', 'top load'] },
    'air conditioners':             { categories: ['appliances'], titleTerms: ['air conditioner', 'ac'] },
    'inverter ac':                  { categories: ['appliances'], titleTerms: ['inverter', 'ac'] },
    'split acs':                    { categories: ['appliances'], titleTerms: ['split', 'ac'] },
    'window acs':                   { categories: ['appliances'], titleTerms: ['window', 'ac'] },
    refrigerators:                  { categories: ['appliances'], titleTerms: ['refrigerator', 'fridge'] },
    'single door':                  { categories: ['appliances'], titleTerms: ['single door', 'refrigerator'] },
    'double door':                  { categories: ['appliances'], titleTerms: ['double door', 'refrigerator'] },
    'triple door':                  { categories: ['appliances'], titleTerms: ['triple door', 'refrigerator'] },
    'side by side':                 { categories: ['appliances'], titleTerms: ['side by side', 'refrigerator'] },
    convertible:                    { categories: ['appliances'], titleTerms: ['convertible', 'refrigerator'] },
    'kitchen appliances':           { categories: ['appliances'], titleTerms: ['kitchen'] },
    'microwave ovens':              { categories: ['appliances'], titleTerms: ['microwave'] },
    'oven toaster grills (otg)':    { categories: ['appliances'], titleTerms: ['otg', 'oven', 'toaster', 'grill'] },
    'juicer/mixer/grinder':         { categories: ['appliances'] },
    'electric kettle':              { categories: ['appliances'] },
    'induction cooktops':           { categories: ['appliances'] },
    chimneys:                       { categories: ['appliances'] },
    'hand blenders':                { categories: ['appliances'] },
    'sandwich makers':              { categories: ['appliances'] },
    'pop up toasters':              { categories: ['appliances'] },
    'electric cookers':             { categories: ['appliances'] },
    'wet grinders':                 { categories: ['appliances'] },
    'food processors':              { categories: ['appliances'] },
    'coffee makers':                { categories: ['appliances'] },
    dishwashers:                    { categories: ['appliances'] },
    'healthy living appliances':    { categories: ['appliances'] },
    'small home appliances':        { categories: ['appliances'] },
    fans:                           { categories: ['appliances'] },
    'water purifiers':              { categories: ['appliances'] },
    'air coolers':                  { categories: ['appliances'] },
    inverters:                      { categories: ['appliances'] },
    'vacuum cleaners':              { categories: ['appliances'] },
    'sewing machines':              { categories: ['appliances'] },
    'voltage stabilizers':          { categories: ['appliances'] },
    'water geysers':                { categories: ['appliances'] },
    'immersion rods':               { categories: ['appliances'] },
    'air fryers':                   { categories: ['appliances'] },
    'mixer grinder':                { categories: ['appliances'] },
    'kitchen accessories':          { categories: ['kitchen-accessories'] },

    // ── Men ───────────────────────────────────────────────────────────────────
    mens:                           { categories: ['mens-shirts', 'mens-shoes', 'mens-watches'] },
    'mens-shirts':                  { categories: ['mens-shirts'] },
    clothing:                       { categories: ['mens-shirts', 'womens-dresses', 'tops'] },
    't-shirts':                     { categories: ['mens-shirts'] },
    tshirts:                        { categories: ['mens-shirts'] },
    'top wear':                     { categories: ['mens-shirts'] },
    topwear:                        { categories: ['mens-shirts'] },
    'formal shirts':                { categories: ['mens-shirts'] },
    'casual shirts':                { categories: ['mens-shirts'] },
    shirts:                         { categories: ['mens-shirts'], titleTerms: ['shirt', 't-shirt', 'tshirt', 'polo'] },
    shirt:                          { categories: ['mens-shirts'], titleTerms: ['shirt', 't-shirt', 'tshirt', 'polo'] },
    jeans:                          { categories: ['mens-shirts'], titleTerms: ['jeans', 'denim'] },
    'casual trousers':              { categories: ['mens-shirts'], titleTerms: ['trouser', 'pant'] },
    'formal trousers':              { categories: ['mens-shirts'], titleTerms: ['trouser', 'pant'] },
    trousers:                       { categories: ['mens-shirts'], titleTerms: ['trouser', 'pant'] },
    'track pants':                  { categories: ['mens-shirts'], titleTerms: ['track pant', 'jogger'] },
    shorts:                         { categories: ['mens-shirts'], titleTerms: ['shorts'] },
    cargos:                         { categories: ['mens-shirts'], titleTerms: ['cargo'] },
    'three fourths':                { categories: ['mens-shirts'], titleTerms: ['three fourth'] },
    'suits, blazers & waistcoats':  { categories: ['mens-shirts'], titleTerms: ['suit', 'blazer', 'waistcoat'] },
    'suits, blazers':               { categories: ['mens-shirts'], titleTerms: ['suit', 'blazer'] },
    'ties, socks, caps & more':     { categories: ['mens-shirts'], titleTerms: ['tie', 'sock', 'cap'] },
    fabrics:                        { categories: ['mens-shirts'], titleTerms: ['fabric'] },
    'winter wear':                  { categories: ['mens-shirts'], titleTerms: ['winter', 'jacket', 'sweater', 'sweatshirt'] },
    sweatshirts:                    { categories: ['mens-shirts'], titleTerms: ['sweatshirt', 'hoodie'] },
    jackets:                        { categories: ['mens-shirts'], titleTerms: ['jacket'] },
    sweater:                        { categories: ['mens-shirts'], titleTerms: ['sweater'] },
    tracksuits:                     { categories: ['mens-shirts'], titleTerms: ['tracksuit'] },
    'ethnic wear':                  { categories: ['mens-shirts', 'sarees', 'kurtas', 'lehengas'] },
    sherwanis:                      { categories: ['mens-shirts'] },
    'ethnic pyjama':                { categories: ['mens-shirts'] },
    dhoti:                          { categories: ['mens-shirts'] },
    lungi:                          { categories: ['mens-shirts'] },
    'innerwear & loungewear':       { categories: ['mens-shirts'] },
    innerwear:                      { categories: ['mens-shirts'] },
    'briefs & trunks':              { categories: ['mens-shirts'] },
    vests:                          { categories: ['mens-shirts'] },
    boxers:                         { categories: ['mens-shirts'] },
    'pyjamas and lounge pants':     { categories: ['mens-shirts'] },
    thermals:                       { categories: ['mens-shirts'] },
    'night suits':                  { categories: ['mens-shirts'] },
    'raincoats & windcheaters':     { categories: ['mens-shirts'] },
    'footwear':                     { categories: ['mens-shoes', 'womens-shoes'] },
    'shoe':                         { categories: ['mens-shoes', 'womens-shoes'] },
    'shoes':                        { categories: ['mens-shoes', 'womens-shoes'] },
    'shooes':                       { categories: ['mens-shoes', 'womens-shoes'] },
    'mens-shoes':                   { categories: ['mens-shoes'] },
    'sports shoes':                 { categories: ['mens-shoes', 'sports-accessories'] },
    'casual shoes':                 { categories: ['mens-shoes'] },
    'formal shoes':                 { categories: ['mens-shoes'] },
    'sandals & floaters':           { categories: ['mens-shoes'] },
    sandals:                        { categories: ['mens-shoes', 'womens-shoes'] },
    'flip-flops':                   { categories: ['mens-shoes'] },
    loafers:                        { categories: ['mens-shoes'] },
    boots:                          { categories: ['mens-shoes', 'womens-shoes'] },
    'running shoes':                { categories: ['mens-shoes'] },
    sneakers:                       { categories: ['mens-shoes'] },
    'mens-watches':                 { categories: ['mens-watches'] },
    watches:                        { categories: ['mens-watches', 'womens-watches'] },
    sunglasses:                     { categories: ['sunglasses', 'mens-watches'] },
    backpacks:                      { categories: ['sports-accessories', 'mobile-accessories'] },
    wallets:                        { categories: ['mens-watches'] },
    belts:                          { categories: ['mens-watches'] },
    deodorants:                     { categories: ['fragrances'] },
    fragrances:                     { categories: ['fragrances'] },
    perfumes:                       { categories: ['fragrances'] },
    trimmers:                       { categories: ['mobile-accessories'] },
    shavers:                        { categories: ['mobile-accessories'] },
    'grooming kits':                { categories: ['mobile-accessories'] },
    "men's grooming":               { categories: ['fragrances', 'mobile-accessories'] },
    'beard care & grooming':        { categories: ['fragrances'] },
    'shaving & aftershave':         { categories: ['fragrances'] },
    'sexual wellness':              { categories: ['skin-care'] },
    'sports & fitness store':       { categories: ['sports-accessories'] },
    'personal care appliances':     { categories: ['mobile-accessories'] },

    // ── Women ─────────────────────────────────────────────────────────────────
    womens:                         { categories: ['womens-dresses', 'womens-shoes', 'womens-watches', 'womens-bags', 'womens-jewellery', 'tops', 'sarees', 'kurtas', 'lehengas'] },
    'womens-dresses':               { categories: ['womens-dresses'] },
    dresses:                        { categories: ['womens-dresses'] },
    tops:                           { categories: ['tops'] },
    'women western & maternity wear':{ categories: ['womens-dresses', 'tops'] },
    'lingerie & sleepwear':         { categories: ['womens-dresses'] },
    bras:                           { categories: ['womens-dresses'] },
    panties:                        { categories: ['womens-dresses'] },
    'lingerie sets':                { categories: ['womens-dresses'] },
    'night dresses & nighties':     { categories: ['womens-dresses'] },
    shapewear:                      { categories: ['womens-dresses'] },
    'camisoles & slips':            { categories: ['womens-dresses'] },
    'swim & beachwear':             { categories: ['womens-dresses'] },
    'party dresses':                { categories: ['womens-dresses'] },
    'sports wear':                  { categories: ['sports-accessories', 'womens-dresses'] },
    skirts:                         { categories: ['womens-dresses'] },
    jeggings:                       { categories: ['womens-dresses'] },
    'jeggings & tights':            { categories: ['womens-dresses'] },
    'trousers & capris':            { categories: ['womens-dresses'] },

    sarees:                         { categories: ['sarees'] },
    'kurtas & kurtis':              { categories: ['kurtas'] },
    kurtis:                         { categories: ['kurtas'] },
    kurtas:                         { categories: ['kurtas'] },
    'dress material':               { categories: ['sarees', 'kurtas'] },
    'lehenga choli':                { categories: ['lehengas'] },
    lehengas:                       { categories: ['lehengas'] },
    blouse:                         { categories: ['sarees', 'kurtas'] },
    'kurta sets & salwar suits':    { categories: ['kurtas'] },
    gowns:                          { categories: ['womens-dresses'] },
    dupattas:                       { categories: ['kurtas', 'sarees'] },
    'ethnic bottoms':               { categories: ['kurtas'] },
    'leggings & churidars':         { categories: ['kurtas'] },
    palazzos:                       { categories: ['kurtas'] },
    shararas:                       { categories: ['lehengas'] },
    'salwars & patiala':            { categories: ['kurtas'] },
    'dhoti pants':                  { categories: ['kurtas'] },
    'ethnic trousers':              { categories: ['kurtas'] },
    'saree shapewear & petticoats': { categories: ['sarees'] },
    'womens-shoes':                 { categories: ['womens-shoes'] },
    flats:                          { categories: ['womens-shoes'] },
    heels:                          { categories: ['womens-shoes'] },
    wedges:                         { categories: ['womens-shoes'] },
    ballerinas:                     { categories: ['womens-shoes'] },
    'slippers & flip-flops':        { categories: ['womens-shoes'] },
    'womens-watches':               { categories: ['womens-watches'] },
    'skin care':                    { categories: ['skin-care'] },
    skincare:                       { categories: ['skin-care'] },
    'hair care':                    { categories: ['skin-care'] },
    'hair straighteners':           { categories: ['mobile-accessories'] },
    'hair dryers':                  { categories: ['mobile-accessories'] },
    epilators:                      { categories: ['mobile-accessories'] },
    'beauty & grooming':            { categories: ['beauty', 'skin-care'] },
    'make up':                      { categories: ['beauty'] },
    makeup:                         { categories: ['beauty'] },
    beauty:                         { categories: ['beauty', 'skin-care'] },
    'bath & spa':                   { categories: ['skin-care'] },
    'deodorants & perfumes':        { categories: ['fragrances'] },
    jewellery:                      { categories: ['womens-jewellery'] },
    jewelry:                        { categories: ['womens-jewellery'] },
    'artificial jewellery':         { categories: ['womens-jewellery'] },
    'silver jewellery':             { categories: ['womens-jewellery'] },
    'precious jewellery':           { categories: ['womens-jewellery'] },
    'coins and bars':               { categories: ['womens-jewellery'] },
    handbags:                       { categories: ['womens-bags'] },
    'shoulder bags':                { categories: ['womens-bags'] },
    totes:                          { categories: ['womens-bags'] },
    'sling bags':                   { categories: ['womens-bags'] },
    clutches:                       { categories: ['womens-bags'] },
    'wallets & belts':              { categories: ['womens-bags', 'mens-watches'] },
    'luggage & travel':             { categories: ['sports-accessories', 'womens-bags'] },
    frames:                         { categories: ['sunglasses', 'mobile-accessories'] },

    // ── Baby & Kids ───────────────────────────────────────────────────────────
    kids:                           { categories: ['mens-shirts', 'sports-accessories'] },
    "kids' clothing":               { categories: ['mens-shirts'] },
    "boys' clothing":               { categories: ['mens-shirts'] },
    'boys clothing':                { categories: ['mens-shirts'] },
    "girls' clothing":              { categories: ['womens-dresses', 'tops'] },
    'girls clothing':               { categories: ['womens-dresses', 'tops'] },
    "baby boys' clothing":          { categories: ['mens-shirts'] },
    "baby girls' clothing":         { categories: ['womens-dresses'] },
    "kids' footwear":               { categories: ['mens-shoes', 'womens-shoes'] },
    'kids footwear':                { categories: ['mens-shoes', 'womens-shoes'] },
    "boys' footwear":               { categories: ['mens-shoes'] },
    "girls' footwear":              { categories: ['womens-shoes'] },
    'infant footwear':              { categories: ['mens-shoes'] },
    "kids' watches":                { categories: ['mens-watches'] },
    "kids' sunglasses":             { categories: ['sunglasses'] },
    "kids' winter wear":            { categories: ['mens-shirts'] },
    toys:                           { categories: ['sports-accessories'] },
    'remote control toys':          { categories: ['sports-accessories', 'automotive'] },
    'educational toys':             { categories: ['sports-accessories'] },
    'soft toys':                    { categories: ['sports-accessories'] },
    'cars & die-cast vehicles':     { categories: ['sports-accessories', 'automotive'] },
    'outdoor toys':                 { categories: ['sports-accessories'] },
    'action figures':               { categories: ['sports-accessories'] },
    'board games':                  { categories: ['sports-accessories'] },
    'musical toys':                 { categories: ['sports-accessories'] },
    'dolls & doll houses':          { categories: ['sports-accessories'] },
    puzzles:                        { categories: ['sports-accessories'] },
    's.t.e.m toys':                 { categories: ['sports-accessories'] },
    'helicopter & drones':          { categories: ['sports-accessories', 'mobile-accessories'] },
    'toy guns':                     { categories: ['sports-accessories'] },
    'party supplies':               { categories: ['sports-accessories'] },
    'school bags':                  { categories: ['sports-accessories', 'mobile-accessories'] },
    'school combo sets':            { categories: ['sports-accessories'] },
    'lunch box':                    { categories: ['kitchen-accessories'] },
    'lunch boxes':                  { categories: ['kitchen-accessories'] },
    'baby care':                    { categories: ['skin-care', 'groceries'] },
    diapers:                        { categories: ['groceries', 'skin-care'] },
    wipes:                          { categories: ['skin-care', 'groceries'] },
    'baby food':                    { categories: ['groceries'] },
    'baby skincare':                { categories: ['skin-care'] },
    strollers:                      { categories: ['sports-accessories'] },

    // ── Home & Furniture ──────────────────────────────────────────────────────
    home:                           { categories: ['home-decoration', 'furniture'] },
    'home & furniture':             { categories: ['home-decoration', 'furniture'] },
    furniture:                      { categories: ['furniture'] },
    sofas:                          { categories: ['furniture'] },
    sofa:                           { categories: ['furniture'] },
    'sofa beds':                    { categories: ['furniture'] },
    beds:                           { categories: ['furniture'] },
    mattresses:                     { categories: ['furniture'] },
    wardrobes:                      { categories: ['furniture'] },
    'collapsible wardrobes':        { categories: ['furniture'] },
    'tv units':                     { categories: ['furniture'] },
    'dining tables & chairs':       { categories: ['furniture'] },
    'coffee tables':                { categories: ['furniture'] },
    'shoe racks':                   { categories: ['furniture'] },
    'bean bags':                    { categories: ['furniture'] },
    'office & study furniture':     { categories: ['furniture'] },
    'kids room furniture':          { categories: ['furniture'] },
    'diy furniture':                { categories: ['furniture'] },
    'bedroom furniture':            { categories: ['furniture'] },
    'living room furniture':        { categories: ['furniture'] },
    'home-decoration':              { categories: ['home-decoration'] },
    bedsheets:                      { categories: ['home-decoration'] },
    curtains:                       { categories: ['home-decoration'] },
    'cushions & pillows':           { categories: ['home-decoration'] },
    blankets:                       { categories: ['home-decoration'] },
    'bath towels':                  { categories: ['home-decoration'] },
    'kitchen & table linen':        { categories: ['home-decoration', 'kitchen-accessories'] },
    'floor coverings':              { categories: ['home-decoration'] },
    'smart security system':        { categories: ['mobile-accessories'] },
    'smart door locks':             { categories: ['mobile-accessories'] },
    'home improvement':             { categories: ['home-decoration'] },
    'lawn & gardening':             { categories: ['home-decoration', 'sports-accessories'] },
    paintings:                      { categories: ['home-decoration'] },
    clocks:                         { categories: ['home-decoration'] },
    'wall shelves':                 { categories: ['home-decoration'] },
    stickers:                       { categories: ['home-decoration'] },
    'showpieces & figurines':       { categories: ['home-decoration'] },
    bulbs:                          { categories: ['home-decoration'] },
    'wall lamp':                    { categories: ['home-decoration'] },
    'table lamp':                   { categories: ['home-decoration'] },
    'ceiling lamp':                 { categories: ['home-decoration'] },
    'home decor':                   { categories: ['home-decoration'] },
    'home lighting':                { categories: ['home-decoration'] },
    pans:                           { categories: ['kitchen-accessories'] },
    tawas:                          { categories: ['kitchen-accessories'] },
    'pressure cookers':             { categories: ['kitchen-accessories'] },
    'kitchen tools':                { categories: ['kitchen-accessories'] },
    'gas stoves':                   { categories: ['kitchen-accessories'] },
    'coffee mugs':                  { categories: ['kitchen-accessories'] },
    'dinner set':                   { categories: ['kitchen-accessories'] },
    barware:                        { categories: ['kitchen-accessories'] },
    'water bottles':                { categories: ['kitchen-accessories'] },
    flasks:                         { categories: ['kitchen-accessories'] },
    casseroles:                     { categories: ['kitchen-accessories'] },
    'kitchen containers':           { categories: ['kitchen-accessories'] },
    'kitchen & dining':             { categories: ['kitchen-accessories'] },
    'kitchen, cookware & serveware':{ categories: ['kitchen-accessories'] },
    dogs:                           { categories: ['groceries'] },
    cats:                           { categories: ['groceries'] },
    'fish & aquatics':              { categories: ['groceries'] },
    'pet supplies':                 { categories: ['groceries'] },

    // ── Sports, Books & More ──────────────────────────────────────────────────
    sports:                         { categories: ['sports-accessories', 'motorcycle', 'automotive'] },
    'sports-accessories':           { categories: ['sports-accessories'] },
    'sports, books & more':         { categories: ['sports-accessories', 'books', 'automotive'] },
    cricket:                        { categories: ['sports-accessories'] },
    badminton:                      { categories: ['sports-accessories'] },
    cycling:                        { categories: ['sports-accessories'] },
    football:                       { categories: ['sports-accessories'] },
    skating:                        { categories: ['sports-accessories'] },
    'camping & hiking':             { categories: ['sports-accessories'] },
    swimming:                       { categories: ['sports-accessories'] },
    tennis:                         { categories: ['sports-accessories'] },
    'exercise fitness':             { categories: ['sports-accessories'] },
    'cardio equipment':             { categories: ['sports-accessories'] },
    'home gyms':                    { categories: ['sports-accessories'] },
    dumbbells:                      { categories: ['sports-accessories'] },
    'ab exercisers':                { categories: ['sports-accessories'] },
    'shakers & sippers':            { categories: ['sports-accessories'] },
    'yoga mat':                     { categories: ['sports-accessories'] },
    'yoga & fitness':               { categories: ['sports-accessories'] },
    'gym gloves':                   { categories: ['sports-accessories'] },
    books:                          { categories: ['books'], excludeTitlePatterns: ['macbook', 'matebook', 'notebook', 'facebook', 'chromebook'] },
    book:                           { categories: ['books'], excludeTitlePatterns: ['macbook', 'matebook', 'notebook', 'facebook', 'chromebook'] },
    'entrance exams':               { categories: ['books'] },
    academics:                      { categories: ['books'] },
    'literature & fiction':         { categories: ['books'] },
    fiction:                        { categories: ['books'] },
    'non-fiction':                  { categories: ['books'] },
    'young readers':                { categories: ['books'] },
    'self-help':                    { categories: ['books'] },
    'e-learning':                   { categories: ['books'] },
    'indian languages':             { categories: ['books'] },
    stationery:                     { categories: ['mobile-accessories'] },
    pens:                           { categories: ['mobile-accessories'] },
    diaries:                        { categories: ['mobile-accessories'] },
    'musical instruments':          { categories: ['sports-accessories'] },
    guitars:                        { categories: ['sports-accessories'] },
    'gaming consoles':              { categories: ['mobile-accessories', 'laptops'] },
    'gaming accessories':           { categories: ['mobile-accessories', 'laptops'] },
    'ps4 games':                    { categories: ['mobile-accessories'] },
    music:                          { categories: ['sports-accessories'] },

    // ── Food & Grocery ─────────────────────────────────────────────────────────
    groceries:                      { categories: ['groceries'] },
    'food essentials':              { categories: ['groceries'] },
    'nuts & dry fruits':            { categories: ['groceries'] },
    'tea, coffee and beverages':    { categories: ['groceries'] },
    chocolates:                     { categories: ['groceries'] },
    'snacks corner':                { categories: ['groceries'] },
    'health & nutrition':           { categories: ['groceries', 'skin-care'] },
    'protein supplements':          { categories: ['groceries'] },
    'vitamin supplements':          { categories: ['groceries'] },
    'health drinks':                { categories: ['groceries'] },
    'ayurvedic supplements':        { categories: ['groceries'] },

    // ── Automotive ────────────────────────────────────────────────────────────
    automotive:                     { categories: ['motorcycle', 'automotive'] },
    motorcycle:                     { categories: ['motorcycle'] },
    'auto accessories':             { categories: ['automotive', 'motorcycle'] },
    'helmets & riding gears':       { categories: ['motorcycle', 'sports-accessories'] },
    helmet:                         { categories: ['motorcycle', 'sports-accessories'] },
    'car audio/video':              { categories: ['automotive'] },
    'car mobile accessories':       { categories: ['automotive', 'mobile-accessories'] },
    'car & bike care':              { categories: ['automotive', 'motorcycle'] },
    'vehicle lubricants':           { categories: ['automotive', 'motorcycle'] },

    // ── Medical ───────────────────────────────────────────────────────────────
    'pregnancy and fertility kits': { categories: ['skin-care', 'groceries'] },
    'hot water bag':                { categories: ['kitchen-accessories'] },
};

export function resolveSearchProfile(search?: string): SearchProfile | null {
    if (!search?.trim()) return null;
    let key = search.trim().toLowerCase();
    
    // Direct match
    if (SEARCH_PROFILES[key]) {
        return SEARCH_PROFILES[key];
    }

    // Common variant normalization
    if (key === 'shooes' || key === 'shoe' || key === 'shoes') {
        return SEARCH_PROFILES['footwear'];
    }
    if (key === 'mobile') {
        return SEARCH_PROFILES['mobiles'];
    }

    // Trailing 'ies' and 'y' variations (e.g. battery -> batteries, accessory -> accessories)
    if (key.endsWith('ies')) {
        const sing = key.slice(0, -3) + 'y';
        if (SEARCH_PROFILES[sing]) return SEARCH_PROFILES[sing];
    }
    if (key.endsWith('y')) {
        const plur = key.slice(0, -1) + 'ies';
        if (SEARCH_PROFILES[plur]) return SEARCH_PROFILES[plur];
    }
    
    // Trailing 'es' variations (e.g. dress -> dresses, watch -> watches)
    if (key.endsWith('es')) {
        const sing = key.slice(0, -2);
        if (SEARCH_PROFILES[sing]) return SEARCH_PROFILES[sing];
    }
    if (!key.endsWith('s')) {
        const plur = key + 'es';
        if (SEARCH_PROFILES[plur]) return SEARCH_PROFILES[plur];
    }

    // Trailing 's' plural/singular variations
    if (key.endsWith('s')) {
        const sing = key.slice(0, -1);
        if (SEARCH_PROFILES[sing]) return SEARCH_PROFILES[sing];
    }
    if (!key.endsWith('s')) {
        const plur = key + 's';
        if (SEARCH_PROFILES[plur]) return SEARCH_PROFILES[plur];
    }
    
    return null;
}
